import type { CountryMeta, Language } from '../types/economics'

/**
 * Japanese localized names for tracked global economies.
 */
export const COUNTRY_NAMES_JA: Record<string, string> = {
  USA: 'アメリカ (米国)',
  CHN: '中国',
  DEU: 'ドイツ',
  JPN: '日本',
  IND: 'インド',
  GBR: 'イギリス (英国)',
  FRA: 'フランス',
  ITA: 'イタリア',
  BRA: 'ブラジル',
  CAN: 'カナダ',
  RUS: 'ロシア',
  MEX: 'メキシコ',
  AUS: 'オーストラリア',
  KOR: '韓国',
  ESP: 'スペイン',
  IDN: 'インドネシア',
  TUR: 'トルコ',
  NLD: 'オランダ',
  SAU: 'サウジアラビア',
  CHE: 'スイス',
  POL: 'ポーランド',
  ARG: 'アルゼンチン',
  SWE: 'スウェーデン',
  BEL: 'ベルギー',
  NOR: 'ノルウェー',
  IRL: 'アイルランド',
  ISR: 'イスラエル',
  SGP: 'シンガポール',
  ARE: 'アラブ首長国連邦 (UAE)',
  AUT: 'オーストリア',
  THA: 'タイ',
  MYS: 'マレーシア',
  PHL: 'フィリピン',
  BGD: 'バングラデシュ',
  VNM: 'ベトナム',
  EGY: 'エジプト',
  ZAF: '南アフリカ',
  CHL: 'チリ',
  COL: 'コロンビア',
  FIN: 'フィンランド',
  CZE: 'チェコ',
  PRT: 'ポルトガル',
  ROU: 'ルーマニア',
  PER: 'ペルー',
  NZL: 'ニュージーランド',
  GRC: 'ギリシャ',
  QAT: 'カタール',
  KAZ: 'カザフスタン',
  DZA: 'アルジェリア',
  KWT: 'クウェート',
  MAR: 'モロッコ',
  UKR: 'ウクライナ',
  HUN: 'ハンガリー',
  NGA: 'ナイジェリア',
  DNK: 'デンマーク',
  HKG: '香港',
  TWN: '台湾',
  PAK: 'パキスタン',
  IRN: 'イラン',
  IRQ: 'イラク',
  ETH: 'エチオピア',
  SVK: 'スロバキア',
  PRI: 'プエルトリコ',
  DOM: 'ドミニカ共和国',
  ECU: 'エクアドル',
  UZB: 'ウズベキスタン',
  VEN: 'ベネズエラ',
  AGO: 'アンゴラ',
  KEN: 'ケニア',
  BGR: 'ブルガリア',
  GTM: 'グアテマラ',
  LKA: 'スリランカ',
  CRI: 'コスタリカ',
  LUX: 'ルクセンブルク',
  HRV: 'クロアチア',
  SRB: 'セルビア',
  CIV: 'コートジボワール',
  PAN: 'パナマ',
  LTU: 'リトアニア',
  GHA: 'ガーナ',
  URY: 'ウルグアイ',
  TZA: 'タンザニア',
  BLR: 'ベラルーシ',
  MMR: 'ミャンマー',
  COD: 'コンゴ民主共和国',
  AZE: 'アゼルバイジャン',
  SVN: 'スロベニア',
  TKM: 'トルクメニスタン',
  JOR: 'ヨルダン',
  UGA: 'ウガンダ',
  BOL: 'ボリビア',
  CMR: 'カメルーン',
  TUN: 'チュニジア',
  MAC: 'マカオ',
  BHR: 'バーレーン',
  LVA: 'ラトビア',
  EST: 'エストニア',
  ISL: 'アイスランド',
  CYP: 'キプロス',
}

/**
 * Japanese localized currency names.
 */
export const CURRENCY_NAMES_JA: Record<string, string> = {
  USD: '米ドル',
  EUR: 'ユーロ',
  KRW: '韓国ウォン',
  JPY: '日本円',
  GBP: '英ポンド',
  CNY: '中国人民元',
  INR: 'インドルピー',
  BRL: 'ブラジルレアル',
  CAD: 'カナダドル',
  RUB: 'ロシアルーブル',
  MXN: 'メキシコペソ',
  AUD: '豪ドル',
  TRY: 'トルコリラ',
  IDR: 'インドネシアルピア',
  SAR: 'サウジリヤル',
  CHF: 'スイスフラン',
  PLN: 'ポーランドズウォティ',
  ARS: 'アルゼンチンペソ',
  SEK: 'スウェーデンクローナ',
  NOK: 'ノルウェークローネ',
  ILS: 'イスラエルシェケル',
  SGD: 'シンガポールドル',
  AED: 'UAEディルハム',
  THB: 'タイバーツ',
  MYR: 'マレーシアリンギット',
  PHP: 'フィリピンペソ',
  BDT: 'バングラデシュタカ',
  VND: 'ベトナムドン',
  EGP: 'エジプトポンド',
  ZAR: '南アフリカランド',
  CLP: 'チリペソ',
  COP: 'コロンビアペソ',
  CZK: 'チェココルナ',
  RON: 'ルーマニアレウ',
  PEN: 'ペルーソル',
  NZD: 'NZドル',
  QAR: 'カタールリヤル',
  KZT: 'カザフスタンテゲ',
  DZD: 'アルジェリアディナール',
  KWD: 'クウェートディナール',
  MAD: 'モロッコディルハム',
  UAH: 'ウクライナフリヴニャ',
  HUF: 'ハンガリーフォリント',
  NGN: 'ナイジェリアナイラ',
  DKK: 'デンマーククローネ',
  HKD: '香港ドル',
  TWD: 'ニュー台湾ドル',
  PKR: 'パキスタンルピー',
  LKR: 'スリランカルピー',
  CRC: 'コスタリカコロン',
  RSD: 'セルビアディナール',
  XOF: '西アフリカCFAフラン',
  GHS: 'ガーナセディ',
  UYU: 'ウルグアイペソ',
  TZS: 'タンザニアシリング',
  BYN: 'ベラルーシルーブル',
  MMK: 'ミャンマチャット',
  CDF: 'コンゴフラン',
  AZN: 'アゼルバイジャンマナト',
  TMT: 'トルクメニスタンマナト',
  JOD: 'ヨルダンディナール',
  UGX: 'ウガンダシリング',
  BOB: 'ボリビアーノ',
  XAF: '中央アフリカCFAフラン',
  TND: 'チュニジアディナール',
  MOP: 'マカオパタカ',
  BHD: 'バーレーンディナール',
  ISK: 'アイスランドクローナ',
}

/**
 * Spanish localized names for tracked global economies.
 */
export const COUNTRY_NAMES_ES: Record<string, string> = {
  USA: 'Estados Unidos',
  CHN: 'China',
  DEU: 'Alemania',
  JPN: 'Japón',
  IND: 'India',
  GBR: 'Reino Unido',
  FRA: 'Francia',
  ITA: 'Italia',
  BRA: 'Brasil',
  CAN: 'Canadá',
  RUS: 'Rusia',
  MEX: 'México',
  AUS: 'Australia',
  KOR: 'Corea del Sur',
  ESP: 'España',
  IDN: 'Indonesia',
  TUR: 'Turquía',
  NLD: 'Países Bajos',
  SAU: 'Arabia Saudita',
  CHE: 'Suiza',
  POL: 'Polonia',
  ARG: 'Argentina',
  SWE: 'Suecia',
  BEL: 'Bélgica',
  NOR: 'Noruega',
  IRL: 'Irlanda',
  ISR: 'Israel',
  SGP: 'Singapur',
  ARE: 'Emiratos Árabes Unidos',
  AUT: 'Austria',
  THA: 'Tailandia',
  MYS: 'Malasia',
  PHL: 'Filipinas',
  BGD: 'Bangladés',
  VNM: 'Vietnam',
  EGY: 'Egipto',
  ZAF: 'Sudáfrica',
  CHL: 'Chile',
  COL: 'Colombia',
  FIN: 'Finlandia',
  CZE: 'Chequia',
  PRT: 'Portugal',
  ROU: 'Rumania',
  PER: 'Perú',
  NZL: 'Nueva Zelanda',
  GRC: 'Grecia',
  QAT: 'Catar',
  KAZ: 'Kazajistán',
  DZA: 'Argelia',
  KWT: 'Kuwait',
  MAR: 'Marruecos',
  UKR: 'Ucrania',
  HUN: 'Hungría',
  NGA: 'Nigeria',
  DNK: 'Dinamarca',
  HKG: 'Hong Kong',
  TWN: 'Taiwán',
  PAK: 'Pakistán',
  IRN: 'Irán',
  IRQ: 'Irak',
  ETH: 'Etiopía',
  SVK: 'Eslovaquia',
  PRI: 'Puerto Rico',
  DOM: 'República Dominicana',
  ECU: 'Ecuador',
  UZB: 'Uzbekistán',
  VEN: 'Venezuela',
  AGO: 'Angola',
  KEN: 'Kenia',
  BGR: 'Bulgaria',
  GTM: 'Guatemala',
  LKA: 'Sri Lanka',
  CRI: 'Costa Rica',
  LUX: 'Luxemburgo',
  HRV: 'Croacia',
  SRB: 'Serbia',
  CIV: 'Costa de Marfil',
  PAN: 'Panamá',
  LTU: 'Lituania',
  GHA: 'Ghana',
  URY: 'Uruguay',
  TZA: 'Tanzania',
  BLR: 'Bielorrusia',
  MMR: 'Myanmar',
  COD: 'R.D. del Congo',
  AZE: 'Azerbaiyán',
  SVN: 'Eslovenia',
  TKM: 'Turkmenistán',
  JOR: 'Jordania',
  UGA: 'Uganda',
  BOL: 'Bolivia',
  CMR: 'Camerún',
  TUN: 'Túnez',
  MAC: 'Macao',
  BHR: 'Baréin',
  LVA: 'Letonia',
  EST: 'Estonia',
  ISL: 'Islandia',
  CYP: 'Chipre',
}

/**
 * Chinese (Simplified) localized names for tracked global economies.
 */
export const COUNTRY_NAMES_ZH: Record<string, string> = {
  USA: '美国',
  CHN: '中国',
  DEU: '德国',
  JPN: '日本',
  IND: '印度',
  GBR: '英国',
  FRA: '法国',
  ITA: '意大利',
  BRA: '巴西',
  CAN: '加拿大',
  RUS: '俄罗斯',
  MEX: '墨西哥',
  AUS: '澳大利亚',
  KOR: '韩国',
  ESP: '西班牙',
  IDN: '印度尼西亚',
  TUR: '土耳其',
  NLD: '荷兰',
  SAU: '沙特阿拉伯',
  CHE: '瑞士',
  POL: '波兰',
  ARG: '阿根廷',
  SWE: '瑞典',
  BEL: '比利时',
  NOR: '挪威',
  IRL: '爱尔兰',
  ISR: '以色列',
  SGP: '新加坡',
  ARE: '阿联酋',
  AUT: '奥地利',
  THA: '泰国',
  MYS: '马来西亚',
  PHL: '菲律宾',
  BGD: '孟加拉国',
  VNM: '越南',
  EGY: '埃及',
  ZAF: '南非',
  CHL: '智利',
  COL: '哥伦比亚',
  FIN: '芬兰',
  CZE: '捷克',
  PRT: '葡萄牙',
  ROU: '罗马尼亚',
  PER: '秘鲁',
  NZL: '新西兰',
  GRC: '希腊',
  QAT: '卡塔尔',
  KAZ: '哈萨克斯坦',
  DZA: '阿尔及利亚',
  KWT: '科威特',
  MAR: '摩洛哥',
  UKR: '乌克兰',
  HUN: '匈牙利',
  NGA: '尼日利亚',
  DNK: '丹麦',
  HKG: '中国香港',
  TWN: '中国台湾',
  PAK: '巴基斯坦',
  IRN: '伊朗',
  IRQ: '伊拉克',
  ETH: '埃塞俄比亚',
  SVK: '斯洛伐克',
  PRI: '波多黎各',
  DOM: '多米尼加共和国',
  ECU: '厄瓜多尔',
  UZB: '乌兹别克斯坦',
  VEN: '委内瑞拉',
  AGO: '安哥拉',
  KEN: '肯尼亚',
  BGR: '保加利亚',
  GTM: '危地马拉',
  LKA: '斯里兰卡',
  CRI: '哥斯达黎加',
  LUX: '卢森堡',
  HRV: '克罗地亚',
  SRB: '塞尔维亚',
  CIV: '科特迪瓦',
  PAN: '巴拿马',
  LTU: '立陶宛',
  GHA: '加纳',
  URY: '乌拉圭',
  TZA: '坦桑尼亚',
  BLR: '白俄罗斯',
  MMR: '缅甸',
  COD: '刚果民主共和国',
  AZE: '阿塞拜疆',
  SVN: '斯洛文尼亚',
  TKM: '土库曼斯坦',
  JOR: '约旦',
  UGA: '乌干达',
  BOL: '玻利维亚',
  CMR: '喀麦隆',
  TUN: '突尼斯',
  MAC: '中国澳门',
  BHR: '巴林',
  LVA: '拉脱维亚',
  EST: '爱沙尼亚',
  ISL: '冰岛',
  CYP: '塞浦路斯',
}

/**
 * Spanish localized currency names.
 */
export const CURRENCY_NAMES_ES: Record<string, string> = {
  USD: 'Dólar estadounidense',
  EUR: 'Euro',
  KRW: 'Won surcoreano',
  JPY: 'Yen japonés',
  GBP: 'Libra esterlina',
  CNY: 'Yuan chino',
  INR: 'Rupia india',
  BRL: 'Real brasileño',
  CAD: 'Dólar canadiense',
  RUB: 'Rublo ruso',
  MXN: 'Peso mexicano',
  AUD: 'Dólar australiano',
  TRY: 'Lira turca',
  IDR: 'Rupia indonesia',
  SAR: 'Riyal saudí',
  CHF: 'Franco suizo',
  PLN: 'Złoty polaco',
  ARS: 'Peso argentino',
  SEK: 'Corona sueca',
  NOK: 'Corona noruega',
  ILS: 'Nuevo séquel israelí',
  SGD: 'Dólar de Singapur',
  AED: 'Dírham de los EAU',
  THB: 'Baht tailandés',
  MYR: 'Ringgit malayo',
  PHP: 'Peso filipino',
  BDT: 'Taka de Bangladés',
  VND: 'Dong vietnamita',
  EGP: 'Libra egipcia',
  ZAR: 'Rand sudafricano',
  CLP: 'Peso chileno',
  COP: 'Peso colombiano',
  CZK: 'Corona checa',
  RON: 'Leu rumano',
  PEN: 'Sol peruano',
  NZD: 'Dólar neozelandés',
  QAR: 'Riyal catarí',
  KZT: 'Tenge kazajo',
  DZD: 'Dinar argelino',
  KWD: 'Dinar kuwaití',
  MAD: 'Dírham marroquí',
  UAH: 'Grivna ucraniana',
  HUF: 'Forinto húngaro',
  NGN: 'Naira nigeriana',
  DKK: 'Corona danesa',
  HKD: 'Dólar de Hong Kong',
  TWD: 'Nuevo dólar taiwanés',
  PKR: 'Rupia pakistaní',
  LKR: 'Rupia de Sri Lanka',
  CRC: 'Colón costarricense',
  RSD: 'Dinar serbio',
  XOF: 'Franco CFA de África Occidental',
  GHS: 'Cedi ghanés',
  UYU: 'Peso uruguayo',
  TZS: 'Chelín tanzano',
  BYN: 'Rublo bielorruso',
  MMK: 'Kyat birmano',
  CDF: 'Franco congoleño',
  AZN: 'Manat azerbaiyano',
  TMT: 'Manat turcomano',
  JOD: 'Dinar jordano',
  UGX: 'Chelín ugandés',
  BOB: 'Boliviano',
  XAF: 'Franco CFA de África Central',
  TND: 'Dinar tunecino',
  MOP: 'Pataca de Macao',
  BHD: 'Dinar bareiní',
  ISK: 'Corona islandesa',
}

/**
 * Chinese (Simplified) localized currency names.
 */
export const CURRENCY_NAMES_ZH: Record<string, string> = {
  USD: '美元',
  EUR: '欧元',
  KRW: '韩元',
  JPY: '日元',
  GBP: '英镑',
  CNY: '人民币',
  INR: '印度卢比',
  BRL: '巴西雷亚尔',
  CAD: '加拿大元',
  RUB: '俄罗斯卢布',
  MXN: '墨西哥比索',
  AUD: '澳大利亚元',
  TRY: '土耳其里拉',
  IDR: '印尼卢比',
  SAR: '沙特里亚尔',
  CHF: '瑞士法郎',
  PLN: '波兰兹罗提',
  ARS: '阿根廷比索',
  SEK: '瑞典克朗',
  NOK: '挪威克朗',
  ILS: '以色列新谢克尔',
  SGD: '新加坡元',
  AED: '阿联酋迪拉姆',
  THB: '泰铢',
  MYR: '马来西亚林吉特',
  PHP: '菲律宾比索',
  BDT: '孟加拉塔卡',
  VND: '越南盾',
  EGP: '埃及镑',
  ZAR: '南非兰特',
  CLP: '智利比索',
  COP: '哥伦比亚比索',
  CZK: '捷克克朗',
  RON: '罗马尼亚列伊',
  PEN: '秘鲁索尔',
  NZD: '新西兰元',
  QAR: '卡塔尔里亚尔',
  KZT: '哈萨克斯坦坚戈',
  DZD: '阿尔及利亚第纳尔',
  KWD: '科威特第纳尔',
  MAD: '摩洛哥迪拉姆',
  UAH: '乌克兰格里夫纳',
  HUF: '匈牙利福林',
  NGN: '尼日利亚奈拉',
  DKK: '丹麦克朗',
  HKD: '港元',
  TWD: '新台币',
  PKR: '巴基斯坦卢比',
  LKR: '斯里兰卡卢比',
  CRC: '哥斯达黎加科朗',
  RSD: '塞尔维亚第纳尔',
  XOF: '西非法郎',
  GHS: '加纳塞地',
  UYU: '乌拉圭比索',
  TZS: '坦桑尼亚先令',
  BYN: '白俄罗斯卢布',
  MMK: '缅甸元',
  CDF: '刚果法郎',
  AZN: '阿塞拜疆马纳特',
  TMT: '土库曼斯坦马纳特',
  JOD: '约旦第纳尔',
  UGX: '乌干达先令',
  BOB: '玻利维亚诺',
  XAF: '中非法郎',
  TND: '突尼斯第纳尔',
  MOP: '澳门元',
  BHD: '巴林第纳尔',
  ISK: '冰岛克朗',
}

/**
 * Returns country display name based on current language.
 */
export function getCountryName(country: CountryMeta, lang: Language): string {
  if (lang === 'ko') return country.nameKo
  if (lang === 'ja') return COUNTRY_NAMES_JA[country.id] || country.nameJa || country.nameEn
  if (lang === 'es') return COUNTRY_NAMES_ES[country.id] || country.nameEs || country.nameEn
  if (lang === 'zh') return COUNTRY_NAMES_ZH[country.id] || country.nameZh || country.nameEn
  return country.nameEn
}

/**
 * Returns secondary name (e.g. for subtext or dual display).
 */
export function getCountrySecondaryName(country: CountryMeta, lang: Language): string {
  if (lang === 'en') return country.nameKo
  return country.nameEn
}

/**
 * Returns currency display name based on current language.
 */
export function getCurrencyName(country: CountryMeta, lang: Language): string {
  if (lang === 'ko') return country.currencyNameKo
  if (lang === 'ja') return CURRENCY_NAMES_JA[country.currencyCode] || country.currencyNameJa || country.currencyNameEn
  if (lang === 'es') return CURRENCY_NAMES_ES[country.currencyCode] || country.currencyNameEs || country.currencyNameEn
  if (lang === 'zh') return CURRENCY_NAMES_ZH[country.currencyCode] || country.currencyNameZh || country.currencyNameEn
  return country.currencyNameEn
}

